let stockProductos = [
    { id: 1, nombre: "America Round Amber", precio: 120, img: "./assets/ARA.webp", stock: 40, cantidad:1 },
    { id: 2, nombre: "America Round Classic", precio: 110,img: "./assets/AMERICAROUND.webp", stock: 20, cantidad:1  },
    { id: 3, nombre: "Big D Constelation Orange", precio: 230,img: "./assets/BIGDCONSTELLATIONORANGE.webp", stock: 50, cantidad:1  },
    { id: 4, nombre: "Big D Constelation", precio: 200,img: "./assets/BIGDCONSTELLATION.webp", stock: 30, cantidad:1 },
    { id: 5, nombre: "Big Montana Black", precio: 180,img: "./assets/BIGDMONTANABLACK.webp", stock: 30, cantidad:1 },
    { id: 6, nombre: "Classic Metal Square Gold", precio: 150,img: "./assets/CLASSICMETALSQUAREGOLD.webp", stock: 20, cantidad:1 },
    { id: 7, nombre: "Doha Square Navy", precio: 150,img: "./assets/DOHASQUARENAVY.webp", stock: 10, cantidad:1 },
    { id: 8, nombre: "Elanor Gol", precio: 200,img: "./assets/ELANORGOL.webp", stock: 30, cantidad:1 },
    { id: 9, nombre: "Hurricane", precio: 240,img: "./assets/HURRICANE.webp", stock: 25, cantidad:1 },
    { id: 10, nombre: "Hurricane Black", precio: 230,img: "./assets/HURRICANEBLACK.webp", stock: 30, cantidad:1 },
    { id: 11, nombre: "Infinity", precio: 200,img: "./assets/infinity.webp", stock: 30, cantidad:1 },
    { id: 12, nombre: "Luxxor Trans Brown", precio: 180, img: "./assets/LUXXOR.webp", stock: 20, cantidad:1 },
    { id: 13, nombre: "Raptor Av Gunmetal", precio: 150,img: "./assets/RAPTORAVGUNMETAL.webp", stock: 10, cantidad:1 },
    { id: 14, nombre: "Roller SQ Champagne", precio: 120,img: "./assets/ROLLERSQCHAMPAGNE.webp", stock: 30, cantidad:1 },
    { id: 15, nombre: "Roosevelt Shiny Blue", precio: 140,img: "./assets/ROOSEVELTSHINYBLUE.webp", stock: 25, cantidad:1 },
    { id: 16, nombre: "Rooselvelt", precio: 150,img: "./assets/ROOSEVELT.webp", stock: 30, cantidad:1 },
    { id: 17, nombre: "Ultra Light S Round Black", precio: 180,img: "./assets/ULTRALIGHTSROUNDBLACK.webp", stock: 30, cantidad:1 },
    { id: 18, nombre: "Ultra Light S Round Crystal Grey", precio: 180,img: "./assets/ULTRALIGHTSROUNDCRYSTALGREY.webp", stock: 20, cantidad:1 },
    { id: 19, nombre: "Walker AV Black", precio: 120,img: "./assets/WALKERAVBLACK.webp", stock: 30, cantidad:1 },
    { id: 20, nombre: "Walker SQ Carey", precio: 140,img: "./assets/WALKERSQCAREY.webp", stock: 25, cantidad:1 },
  ]